### PR TITLE
adding rough draft of documentation for compiling to executable form for distribution.

### PR DESCRIPTION
**Pull request by valiant8086**
See the commit log, this isn't complete yet and I could use some help understanding how this all works on Linux and Mac OS.

### CODE REVIEW

**Comment by valiant8086** [comment]
Oh I see it still shows my previous commit that's already been merged in. This doesn't look right. Don't I need to do something to get it to just be trying to get the last commit in? Should I delete that branch from my fork and make it again? Can definitely tell I'm a noob.

**Comment by valiant8086** [comment]
From the new doc:

Since Nvgt is intended to be able to run on Windows, Linux and Mac OS, there will be different executables for each targeted operating system. The resulting compiled binary will have a certain file extension depending on which opperating system, as follows:
* Windows: *.exe
* Linux: *.
* Mac OS: *.


Notice the Linux and Mac OS don't have their proper file extensions added yet.

**Comment by valiant8086** [comment]
and I don't know what those will be, so if you want to fix that's probably quickest, or I can do another pr for it if you can tell me what they are.

**Comment by samtupy** [comment]
Hi,
So actually the reason those were left blank, and maybe we should still update the doc to make it more clear, is because MacOS and linux libraries have no extension.
For example, compiling game.nvgt to linux produces an extensionless binary just called game. This is similar to all other elf binaries on macos or linux which have no extension. In fact I think it's possible that out of all 5 platforms we intend to support (android and IOS to be added in future), windows might actually be the only platform that ever adds an extension to it's common binary format.
I can update the guide to make that more clear as the confusion makes sense, thanks.

**Pull request merged**
