### PR TITLE
Add support for tabs in audio form

### PR DESCRIPTION
**Pull request by NKPR0d**

### CODE REVIEW

**Comment by kirill-jjj** [comment]
wow, good option. I hope this pull request will be merged

**Comment by samtupy** [comment]
Hi,
Thanks for the contribution!
I need to think on this a bit before we merge it. For example, adding a tab panel without adding the ability to select what controls appear on each tab might be confusing to users who, upon seeing the tab_panel argument of the create_list method, will instantly wonder how they link controls to tabs. This pr does not address that.
Furthermore I need to consider whether we should be overloading the list control to create a tab panel in the first place, and I may conclude that it's fine. However, at the very least we need to create a speak_list_item method in the control class at this point if we do this because the code that speaks list items is duplicated all over the place and just got even longer.
This is an interesting start to the idea and we can certainly see where it goes. Audio form does have the concept of subforms now so it is possible to make different forms appear based on a condition.
If the intent here is to just create a tab_panel control type rather than to integrate entire tab page support, that's fine, but in this case lets create a function called create_tab_panel instead of overloading create_list with an extra boolean argument, as this makes the list overloading blatant in code rather than in just documentation and makes it harder to update the create_list API in the future because we will always be working around the tab_panel argument that most people will only want to use in a few cases in large dialogs. Better to treat it, at least in the external API, as an extra control. In the documentation we can mention that the list functions work on tab panels.
Thanks again it's a start, it will be interesting to see where this goes!

**Comment by peter1384** [comment]
yes please, I also don't like this way. @NKPR0d Please add tabs in a difrent function raather than mixing it in to list, because lists are completely difrent things, and tab controles should be difrent also.

**Comment by NKPR0d** [comment]
Just added create_tab_panel function, but it's still uses the list control type.

**Pull request merged**
