### PR TITLE
Some fixes for tests/quick

### PR DESCRIPTION
**Pull request by deathvelt**
Fixed a few bugs in tests/quick:
changed string d to any@ d = null within the pfc function in tests/quick/PF. This should make the example work. Credit goes to Colonel for his help in figuring it out.
removed the speak function from get_characters (it was included with forms.nvgt).
Replaced KEY_SHIFT with KEY_LSHIFT and KEY_RSHIFT in key_shift.nvgt, as well as correcting ScreenReaderSpeak to screen_reader_speak.
The other fixes are similarly function or property matching related.

### CODE REVIEW

**Comment by samtupy** [comment]
Hi, sorry this is taking a while to merge, basically your pr actually deletes the sound pool from the repository according to the diff. I haven't run into a pr yet where I need to merge most of it and ignore one deleted file, so I need to figure out how to do that before merging this. Thanks for the fixes!

**Comment by deathvelt** [comment]
This happens because while I did make a new branch for this PR in particular, the soundpool PR kept getting added along with the PR. I didn' know what to do so I did git rm --cache sound_pool.nvgt. Now it's doing this, apparently. I can try submitting the PR again if needed, although I still need to figure out how to limit it to the tests only.

**Comment by deathvelt** [comment]
I never included it, actually. I did add them all at first but when I went to the link to send a PR for that particular branch, the soundpool wouldn't stop showing up. I will try rebasing and rePRing, I hope that fixes the problem.

**Comment by deathvelt** [comment]
I believe this PR should be fixed now.

**Pull request merged**
